server:
  port: 8781
eureka:
  instance:
    hostname: localhost
    metadata-map:
      user.name: admin
      user.password: admin
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
spring:
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        exclude:
          include: "*"
  endpoint:
    health:
      show-details: always