server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 是否向自己注册
    registerWithEureka: false
    fetchRegistry: false
    # 服务注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
#logging:
#  path: logs\
#  level:
#    root: info
